### ISSUE TITLE
Run python in_domain_run.py, report errors: NotImplementedError

### ISSUE THREAD

**Issue by Luckypolo2** [Zhang-xie/Wimuse#2]
ENV: pytorch1.8 pytorch lightning1.2.8 python3.8
```python in_domain_run.py``` this command can't work
```shell
/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "in_domain_run.py", line 260, in <module>
    run(args,setting)
  File "in_domain_run.py", line 103, in run
    trainer.fit(model,tr_loader,te_loader)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
    raise NotImplementedError
NotImplementedError
```

**Comment by Luckypolo2** [comment]
> ENV: pytorch1.8 pytorch lightning1.2.8 python3.8 `python in_domain_run.py` this command can't work
> 
> ```shell
> /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
>   warnings.warn(*args, **kwargs)
> Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "in_domain_run.py", line 260, in <module>
>     run(args,setting)
>   File "in_domain_run.py", line 103, in run
>     trainer.fit(model,tr_loader,te_loader)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
>     self.dispatch()
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
>     self.accelerator.start_training(self)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
>     self._results = trainer.run_train()
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
>     self.run_sanity_check(self.lightning_module)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
>     _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
>     for batch_idx, batch in enumerate(dataloader):
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
>     return self.dataset[self.indices[idx]]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
>     raise NotImplementedError
> NotImplementedError
> ```
